#!/usr/bin/env python

"""Regexp pattern for logs generated by RawErasureCoderBenchmark."""
PATTERN_ECB = r"Using (?P<buffer_size>\S+) buffer\.\n(?:.*?\n)*?(?P<coder>.*?) coder (?P<method>\S+?)\s(?P<total_data_size>\S+) data, with chunk size (?P<chunk_size>.*?)\nTotal time: (?P<total_time>.*?)\ss\.\nTotal throughput: (?P<total_throughput>.*?) MB/s\nThreads statistics:\s*(?P<threads_num>.*?) threads in total\.\nMin: (?P<time_min>.*?) s, Max: (?P<time_max>.*?) s, Avg: (?P<time_avg>.*?) s, 90th Percentile: (?P<time_90>.*?) s\."

"""Regexp terms for finding fields in ECB logs"""
FIELDS_ECB = [
    'buffer_size', 'coder', 'method', 'total_data_size', 'chunk_size', 'total_time',
    'total_throughput', 'threads_num', 'time_min', 'time_max', 'time_avg', 'time_90'
]

LOG_TYPES = [
    'ECB-TotalThroughput', 'ECB-Throughput', 'ECB-Latency'
]

__all__ = [
    "PATTERN_ECB",
    "FIELDS_ECB",
]
